//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aozora.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aozora.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   parser encounted author twice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthorTwice {
            get {
                return ResourceManager.GetString("AuthorTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t add 3 ruby ​​characters to one word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DontAllowTripleRuby {
            get {
                return ResourceManager.GetString("DontAllowTripleRuby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A line break occurred in the {0}. Use block notation for elements that straddle line breaks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DontCrlfInStyle {
            get {
                return ResourceManager.GetString("DontCrlfInStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Don&apos;t add 2 ruby ​​characters to the same place に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DontUseDoubleRuby {
            get {
                return ResourceManager.GetString("DontUseDoubleRuby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   encount undefined condition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EncountUndefinedCondition {
            get {
                return ResourceManager.GetString("EncountUndefinedCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error (line {0}):{1}. 
        ///Stoped processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorStop {
            get {
                return ResourceManager.GetString("ErrorStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load JIS X 0213 table. Is embedded resource supported? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FailedToLoadJIS2UCS {
            get {
                return ResourceManager.GetString("FailedToLoadJIS2UCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found the termination of {0}, but not in {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidClosing {
            get {
                return ResourceManager.GetString("InvalidClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified font size is invalid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidFontSize {
            get {
                return ResourceManager.GetString("InvalidFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found the termination of {0}, but in {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidNesting {
            get {
                return ResourceManager.GetString("InvalidNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The rule of repeating notes, &quot;narrow range first, wide range after&quot; is not being followed. Refer to the guideline and fix it に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TagSyntaxError {
            get {
                return ResourceManager.GetString("TagSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The text ended in the {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TerminateInStyle {
            get {
                return ResourceManager.GetString("TerminateInStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found undefined header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UndefinedHeader {
            get {
                return ResourceManager.GetString("UndefinedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found unsupported complex ruby に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnsupportedRuby {
            get {
                return ResourceManager.GetString("UnsupportedRuby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change the line feed code to &quot;CR+LF&quot; (\r\n) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UseCrlf {
            get {
                return ResourceManager.GetString("UseCrlf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning (line {0}): &quot;{1}&quot; is used. Is it misuse of note symbols? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WarnChuki {
            get {
                return ResourceManager.GetString("WarnChuki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning (line {0}): The beginning and end of the hexagonal brackets for accent decomposition are not paired in the line に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WarnInvalidAccentBrancket {
            get {
                return ResourceManager.GetString("WarnInvalidAccentBrancket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning (line {0}): JIS external character &quot;{1}&quot; is used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WarnJisGaiji {
            get {
                return ResourceManager.GetString("WarnJisGaiji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning (line {0}): 1 byte character &quot;{1}&quot; is used に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WarnOnebyte {
            get {
                return ResourceManager.GetString("WarnOnebyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning (line {0}): Unsupported command &quot;{1}&quot;. Ignoring に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WarnUndefinedCommand {
            get {
                return ResourceManager.GetString("WarnUndefinedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning (line {0}): Unexpected end of file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WarnUnexpectedTerminator {
            get {
                return ResourceManager.GetString("WarnUnexpectedTerminator", resourceCulture);
            }
        }
    }
}
